
export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST"
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS"
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER = "USER_REGISTER"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const ADD_CONATCT_REQUIEST = "ADD_CONATCT_REQUIEST"
export const ADD_CONATCT_SUCCESS = "ADD_CONATCT_SUCCESS"
export const ADD_CONATCT_FAIL = "ADD_CONATCT_FAIL"


export const GET_ALL_CONATCT_REQUIEST = "GET_ALL_CONATCT_REQUIEST"
export const GET_ALL_CONATCT_SUCCESS = "GET_ALL_CONATCT_SUCCESS"
export const GET_ALL_CONATCT_FAIL = "GET_ALL_CONATCT_FAIL" 

export const USER_LOGOUT = "USER_LOGOUT" 

export const GET_UPDATE_CONATCT_REQUIEST = "GET_UPDATE_CONATCT_REQUIEST"
export const GET_UPDATE_CONATCT_SUCCESS = "GET_UPDATE_CONATCT_SUCCESS"
export const GET_UPDATE_CONATCT_FAIL = "GET_UPDATE_CONATCT_FAIl"

export const GET_DELETE_CONATCT_REQUIEST = "GET_DELETE_CONATCT_REQUIEST"
export const GET_DELETE_CONATCT_SUCCESS = "GET_DELETE_CONATCT_SUCCESS"
export const GET_DELETE_CONATCT_FAIL = "GET_DELETE_CONATCT_FAIl"